### PR TITLE
Feature/natural log

### PR DESCRIPTION
**Pull request by ahmedar04**

### CODE REVIEW

**Comment by MominHumayon** [comment]
Make sure to add a case for when the input is less than or equal to 0 (the log does not exist)

**Review by MominHumayon — CHANGES_REQUESTED** [review]
Make sure to add a case for when the input is less than or equal to 0 (the log does not exist)

**Comment by ahmedar04** [comment]
added the extra test

**Review by MominHumayon — APPROVED** [review]
Looks good

**Pull request merged**
